sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

matrix:
  include:
    - php: nightly
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0
  allow_failures:
    - php: nightly


# Cache Composer's caches to speed up build times.
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  # Install composer packages before trying to activate themes or plugins
  - composer install

script:
  - composer run test-phpcs
  - composer run test-phpmd
