sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

matrix:
  include:
    - php: nightly
      env: WP_VERSION=master WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=master WP_MULTISITE=0 SNIFF=1
    - php: 7.0
      env: WP_VERSION=master WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=master WP_MULTISITE=0
  allow_failures:
    - php: nightly


# Cache Composer's caches to speed up build times.
cache:
  directories:
    - $HOME/.composer/cache

before_script:
    # Set up WordPress installation.
  - export WP_DEVELOP_DIR=/tmp/wordpress
  - mkdir -p $WP_DEVELOP_DIR
  # Use the Git mirror of WordPress.
  - git clone --depth=1 --branch="$WP_VERSION" https://github.com/WordPress/WordPress.git $WP_DEVELOP_DIR
  # Move plugin to WordPress diectory..
  - export WP_PLUGIN_SLUG=$(basename $(pwd))
  - export WP_PLUGIN_MU_DIR=$WP_DEVELOP_DIR/wp-content/mu-plugins
  - mkdir -p $WP_PLUGIN_MU_DIR
  - cd ..
  - mv $WP_PLUGIN_SLUG $WP_PLUGIN_MU_DIR
  # Setup WordPress
  - mysql -e "CREATE DATABASE wordpress;" -uroot
  # Install composer packages before trying to activate themes or plugins
  - if [[ "$SNIFF" == "1" ]]; then composer require thoughtsideas/ti-wpcs:^1.1.1; fi

script:
  - ls -la $WP_PLUGIN_MU_DIR/$WP_PLUGIN_SLUG/
  # Only run PHP Code tests on one environment to improve total test time.
  - if [[ "$SNIFF" == "1" ]]; then ./vendor/bin/phpcs $WP_PLUGIN_MU_DIR/$WP_PLUGIN_SLUG/ --standard=$WP_PLUGIN_MU_DIR/$WP_PLUGIN_SLUG/phpcs.xml; fi
  - if [[ "$SNIFF" == "1" ]]; then ./vendor/bin/phpmd $WP_PLUGIN_MU_DIR/$WP_PLUGIN_SLUG/ text ./vendor/thoughtsideas/ti-wpcs/TI-WPMD/ruleset.xml; fi
